# Cấu hình kết nối SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CloudMediaDrive;encrypt=true;trustServerCertificate=true
spring.datasource.username=dinhtung2722005
spring.datasource.password=99887766az
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate/JPA (Tự động tạo bảng dựa trên Entity)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# Cấu hình dung lượng cho cơ chế Parallel Chunked Upload (Mảnh 5MB)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cấu hình thư mục Temp lưu trữ mảnh file
app.storage.temp-dir=/storage/temp
app.storage.base-dir=/storage/media

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=900000
app.storage.temp-dir=/storage/temp
app.storage.base-dir=/storage/media